---
- name: Install fail2ban
  ansible.builtin.package:
    name:
      - "fail2ban"
      - "python3-systemd"
    state: present

- name: Template fail2ban local config
  become: true
  ansible.builtin.template:
    src: "fail2ban.local.j2"
    dest: "/etc/fail2ban/fail2ban.local"
    mode: 0644
  notify: Restart fail2ban

- name: Enable Fail2Ban
  become: yes
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
