---
- name: Install fail2ban
  ansible.builtin.package:
    name:
      - "fail2ban"
      - "python3-systemd"
    state: present

- name: Template fail2ban local config
  become: true
  ansible.builtin.template:
    src: "fail2ban.local.j2"
    dest: "/etc/fail2ban/fail2ban.local"
    mode: 0644
  notify: Restart fail2ban

- name: Set Fail2ban to read systemd logs
  community.general.ini_file:
    path: /etc/fail2ban/jail.conf
    section: sshd
    option: backend
    value: systemd
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'

- name: Enable Fail2Ban
  become: yes
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
