---
- name: Install Ufw
  ansible.builtin.package:
    name: ufw
    state: present

- name: Enable UFW ipv6 Filtering
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    line: IPV6=yes
    regexp: "^IPV6="

- name: Set SSH limiting in UFW
  community.general.ufw:
    rule: limit
    port: "{{ ssh_tcp_port }}"
    proto: tcp
  notify: Restart ufw

- name: Allow UFW Ports
  when: lockdown_ufw_allow_ports is defined
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ lockdown_ufw_allow_ports }}"
  notify: Restart ufw
  tags: [skip_ansible_lint]

- name: Enable UFW
  community.general.ufw:
    state: "{{ 'enabled' if lockdown_ufw_enable  else 'disabled' }}"
  tags: ["skip_ansible_lint"] # Because of state template

- name: Deny Other Ports
  community.general.ufw:
    policy: "{{ 'deny' if lockdown_ufw_enable  else 'allow' }}"
  notify: Restart ufw
  tags: ["skip_ansible_lint"] # Because of state template
