---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart ufw
  community.general.ufw:
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: "fail2ban"
    state: "restarted"

- name: Reboot System
  become: yes
  ansible.builtin.reboot:
    reboot_timeout: 1800
